### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by Maushundb** [faceyspacey/babel-plugin-universal-import#1]
It seems that Uglify isn't compatible with  ES6 syntax and is throwing the following error when trying to run on `universalImport.js`

```
ERROR in main.3b107cd023ec5c3b29b1.js from UglifyJs
Unexpected token: operator (>) [./node_modules/babel-plugin-universal-import/universalImport.js:7,0][main.3b107cd023ec5c3b29b1.js:24366,20]
```

I'm getting this when trying to run `npm run build` on a fresh checkout of your other repo that uses this, https://github.com/faceyspacey/redux-first-router, causing it to fail.

**Comment by faceyspacey** [comment]
it's fixed, pushed, published, and the [redux-first-router-demo](https://github.com/faceyspacey/redux-first-router-demo) has been updated.

Thanks for finding this. Let me know if you need anything else.

**Comment by faceyspacey** [comment]
ps. the issue is that in the babel plugin I add 2 additional small files, and I guess since they're added during babel compilation, babel-loader doesn't know to transpile them. During dev you don't notice this issue because you're not using uglify and in the browser it runs in chrome which supports things like arrow functions. But in prod by the time it gets to uglify it expects it transpiled. Something like that. 

Bigger babel plugins that append files I assume have a build phase for those files so they dont have to code them in es5. In the case of this plugin, the files are so small i dont bother, but i let the arrow functions slip.

...one other thing, i upgraded the demo ur using to not have to use the `resolve` option in Universal Component. That's part of what this plugin does. Very soon you won't have to manually create the hash of dynamically imported components, as Im about to finish the PR to webpack that allows for dynamic calls to `require.resolveWeak`, and the webpack team seems to be enthusiastic about merging my fix:

https://github.com/webpack/webpack/pull/5235

...just in case u were wondering what all this universal-import stuff was all about. It will allow for the single import you see here:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox/tree/master/?module=BJiziDAMUb

but not just in an SPA.

**Comment by Maushundb** [comment]
Awesome that all sounds great, thanks as always for the quick turnaround!
