### ISSUE TITLE
Option to disable CSS warnings

### ISSUE THREAD

**Issue by luisherranz** [faceyspacey/babel-plugin-universal-import#21]
Would you accept a PR to add an option to disable the CSS warnings?

Something like this:
```javascript
{
  "plugins": [
    ["universal-import", {
      "disableCssWarnings": true
    }]
  ]
}
```

**Comment by faceyspacey** [comment]
honestly im not sure. i know i plan to add a `debug` mode and consolidate all these packages. and under debug mode, u got lots more warnings, and info. Basically answers to a lot of the questions I've received in issues debug mode automatically would answer for you. Like what chunks were made, what chunks were found, etc, etc. But I know it won't be a while until I get to the big push on `universal`. I'm working on a big push on RFR/Rudy and have been for some weeks now. 

So that said, i dont wanna introduce things, only to replace them, when things have been working well enough. 

Here's a solution u can do that i occasionally do: 

monkey patch `console.warn` to detect if it receives some of that error text and if it does, dont show it. I do that sorta stuff all the time just to keep my life movin.

**Comment by luisherranz** [comment]
Ok, no problem. We can live with the warnings until the unified version comes out with the debug mode :)
