### ISSUE TITLE
error when setting 'node: false' in webpack config

### ISSUE THREAD

**Issue by lutzk** [faceyspacey/babel-plugin-universal-import#4]
when i set `node: false` (to reduce bytes to transfer)  in my webpack frontend config i get the error:
```
Module not found: Error: Can't resolve 'path' in '__REPLACED__/src/app/universalComponent'
```

this is because the  code transformed by the plugin makes use of `__dirname` in the `path`  key wich is disabled by `node: false`

transformed code:

```
Home: __WEBPACK_IMPORTED_MODULE_4_react_universal_component___default()(__WEBPACK_IMPORTED_MODULE_2_babel_plugin_universal_import_universalImport_js___default()({
  ...
  path: () => __WEBPACK_IMPORTED_MODULE_0_path___default.a.join(__dirname, '../containers/Home'), <------ __dirname
  ...
})
```

its fixed when i set `node` to: 
```
node = {
 Buffer: false,
 __dirname: true, // <------ note its enabled
 __filename: false,
 console: false,
 global: false,
 process: false,
};
```
instead of `false`

i am not sure if this can be "fixed" from your site but i think it would be good to add a note in one of the readmes of the coresponding repos like `react-universal-component`
i could  add a note - just let me kow to wich repos it should be added

**Comment by faceyspacey** [comment]
But it shouldn't actually be calling the `path` function. Is it getting the error statically at build time just for using it?

If it's being called, it would be because you're using `flushModuleIds()` (the older original approach before `flushChunkNames()`, and your server is running in babel (i.e. not webpack), and therefore needs the `path` to determine the module IDs. 

One fix if this isn't a static issue, is basically a `try catch` in the `path` function. If that's the case, I don't suppose you could try adding it to this template string here: https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L10

Perhaps `path` is being called even though it's not being used--because it's not unless you're using a very rare setup which we aren't promoting anymore (flushModuleIds on a babel server). So if it's being called accidentally, that will at least fix it.


...actually here's your issue (best guess): `react-universal-component` thinks its running in babel (and maybe it is), and it's using the `path` even though you're flushing chunk names:

https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L127

I wrote it in a way, so that it still adds module IDs to the buffer, even if you're using chunk names, so you can move quickly back and forth and try each. But this is several months old now, and we have shifted focus to chunk names. So basically code you don't need is being called.

Otherwise, just make sure you're using `externals` correctly so these packages know they're running in webpack. the `webpack-node-externals` package can be flakey. So check the stats when your build occurs to make sure these packages appear there. This may not relate in your issue, but I'm just trying to cover all bases. 

I'm gonna push code in a bit that stops flushing moduleIDs when you're using chunk names. The idea was the array is likely small sets, so why not keep both in case you're trying both and logging both and wondering why one is empty.

**Comment by lutzk** [comment]
its getting the error on the end of the compilation
and then when i refresh the browser there too (there i got the transpiled code from)
i am using flushChunkNames()
my server is compiled with webpack not babel

**Comment by lutzk** [comment]
thats my externals setup:
```
externals: [nodeExternals({
    whitelist: [/^webpack\/hot/, /^react-universal-component/, /^require-universal-module/, /^webpack-flush-chunks/]
})],
```
the error just happend after i switched from `babel-plugin-dual-import` to `babel-plugin-universal-import`

i can add a try / catch later today

**Comment by faceyspacey** [comment]
did you update react-universal-component. try now. it might just work.

**Comment by lutzk** [comment]
latest i was on is `v2.0.20`
will update to latest when i am home today evening

**Comment by lutzk** [comment]
so i updated react-universal-component to the latest in my app - but still the same error
i also did a test with `https://github.com/faceyspacey/universal-demo` and added `node: false` to the `/webpack/client.dev.js`  and got the same error

but i was a bit confused about the instructions on the universal-demo readme:
```
git clone https://github.com/webpack/webpack.git
cd webpack
git checkout https://github.com/webpack/webpack.js.org/pull/1453
```
resulted in
 ```
error: pathspec 'https://github.com/webpack/webpack.js.org/pull/1453' did not match any file(s) known to git.
```
as its the pull to the webpack docs repo not the pull to the weback repo
```
https://github.com/webpack/webpack/pull/5235webpack
```
did you actualy meant that one?
anyway its merged right?
and i co located a fresh clone of weback next to `universal-demo` and could reproduce the error

**Comment by faceyspacey** [comment]
I just updated the demo:

https://github.com/faceyspacey/universal-demo

i set node to false and it works.

the demo now uses a fork of webpack called `webpack-universal`. should only be needed for about a week. Nothing special is needed to get the demo running.

I've noticed that sometimes when people use NPM instead of Yarn dependencies don't update as soon. Somehow they stay stuck to an older patch. Perhaps try yarn.

ps. I think we did solve it, and you're still running an old version of universal component. Check node_modules/react-universal-component/package.json for its version.

Im knockin out for the day. We'll get this addressed asap in one way or another.

**Comment by lutzk** [comment]
i pulled the updated demo from scratch and it works now to set  node: false without error
dont worry i just wanted to report it back to you as i found it
thank you a lot!
closing then

**Comment by lutzk** [comment]
sorry for confusion
i just tested to compile yesterday - that was fine
but now wit a fresh clone of the universal demo setting `node: false`
i getfollowing error  in the browser
```
Uncaught ReferenceError: process is not defined
    at eval (path.js:25)
    at Object.<anonymous> (main.js:2445)
    at __webpack_require__ (bootstrap.js:702)
    at fn (bootstrap.js:115)
    at eval (App.js:7)
    at Object.<anonymous> (main.js:143)
    at __webpack_require__ (bootstrap.js:702)
    at fn (bootstrap.js:115)
    at eval (index.js:19)
    at Object.<anonymous> (main.js:1740)
```
strange when i set:
```
node: {
     Buffer: false,
     __dirname: false,
     __filename: false,
     console: false,
     global: false,
     process: false,
 },
```

it all works - even all is set to false - but that might be a webpack issue

**Comment by lutzk** [comment]
there is no custom code from my side
i just cloned the `https://github.com/faceyspacey/universal-demo` like 10 minutes ago

**Comment by faceyspacey** [comment]
i tested both ways--with the full node object and just with __dirname false, and it worked for me.

**Comment by faceyspacey** [comment]
if 'process' isn't defined, somehow webpack isnt injecting things like `process.env.NODE_ENV`.

**Comment by lutzk** [comment]
yes sorry is a diffrent error is `process` not `__dirname` these time
just in the browser

**Comment by faceyspacey** [comment]
process is being overwritten via the `node:` object. not sure how that got to the browser

**Comment by lutzk** [comment]
yes no idea
but as i can dissable `node` actualy with setting the full object it seems ok
should i close again?

**Comment by lutzk** [comment]
i can just test in the evening again

**Comment by faceyspacey** [comment]
yea, close it.
