### ISSUE TITLE
Dont actually Tranform CSS on SSR

### ISSUE THREAD

**Issue by ScriptedAlchemy** [faceyspacey/babel-plugin-universal-import#40]
Hey dude

Im using your babel-server so i dont need a build on both sides. 
I was able to get scss to work, but ive got some scenarios where i need to provide variables and mixins to each file (global colors and stuff)

As you can imagine the compile fails because the variables are not directly imported 
Is there a way to prevent a transformation from happening but still get the chunk-names for flushing?

**Comment by faceyspacey** [comment]
I'm actually not too sure what you're looking to do, but does this help:

https://github.com/michalkvasnicak/babel-plugin-css-modules-transform

**Comment by ScriptedAlchemy** [comment]
mehh not really, but thank you for taking the time. From one webpack guy to another. ill show you what i mean in webpack lingo ;)

I mean, i guess im being lazy - but this removes human error and lets us make resources globally available

I hope this helps 😆 

```        
   {

                // im adding my own mixins and globals, dont wanna go import them
                // this loader doesnt need to be here if you import your mixins directly per file
                test: /\.(scss|css)$/,
                use: [
                    {
                        loader: 'sass-resources-loader',
                        options: {
                            resources: [
                                // i need these bastards otherwise i dont have mixins or variables
                                path.join(appRoot, '/node_modules/@myCompany/sass-assets/_base-external.scss'),
                                path.join(appRoot, '/src/common/resources.scss')
                            ]
                        }
                    }
                ]
            },

**Comment by faceyspacey** [comment]
I still don't know what you mean by:

> Is there a way to prevent a transformation from happening but still get the chunk-names for flushing?

However, I have used `sass-resources-loader` before. I ended up creating my own solution like the following for full control:


## `prepend-loader`:

```js
const loaderUtils = require('loader-utils')

module.exports = function(source) {
  const { prepend = '' } = loaderUtils.getOptions(this)
  return prepend + '\n' + source
}
```

## collect scss vars/mixins:

```js
const { readFileSync } = require('fs')
const { join } = require('path')
const { sync: glob } = require('glob')

const p = (path) => join(__dirname, '../../..', path)

const colors = { red: 'red', blue: 'blue', foo:  '#9b59b6' }
const primaryColor = colors[process.env.SITE_COLOR]

// join our initial scss so imported files can performantly make use of cached vars/mixins/etc
const joinScss = (rawScss, files) =>
  rawScss + '\n' + files.map(f => readFileSync(f, 'utf8')).join('\n')

module.exports = joinScss(`$brand-primary: ${primaryColor};`, [
  p('vendor/bootstrap/_variables.scss'), // bootstrap
  ...glob(p('vendor/bootstrap/mixins/**/*.scss')),

  p('vendor/theme/_variables.scss'), // bootstrap theme

  p('src/stylesheets/_constants.scss'), // internal
  p('src/stylesheets/_mixins.scss'),
])
````

## Usage (webpack config):

```js
{
        test: /\.scss$/,
        use: [
          MiniCssExtract.loader, // or 'style-loader' -- MiniCssExtract doesnt seem to work for HMR during dev yet
          {
            loader: 'css-loader',
            options: {
              modules: false,
            }
          },
          // 'resolve-url-loader', // if @imported scss files use `url('../../background.jpg')` -- not needed in one-level-deep files imported using ES6
          {
            loader: 'sass-loader',
            options: {
              includePaths: [
                p('mode_modules'),
              ]
            }
          },
          {
            loader: p('webpack/loaders/prepend-loader.js'),
            options: {
              prepend: require('./helpers/cachedScss'),
            },
          },
]
```

## ES6 requires:

```js
require('foo.scss')

requireAll(require.context('../src/', true, /\.(css|scss)$/))

require('bar.scss') // if order matters, use `require` instead of `import` so `requireAll` which does not use `import` is respected

// https://github.com/webpack/docs/wiki/context#context-module-api
function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
}
```

----

Since I see you're using Sass, my hunch is the issues you're running into simply have to do with Sass. I used primarily Stylus + css modules last year, but going forward I'll likely be using Emotion and circumventing a lot of the css related issues. There are a few tradeoffs (especially when it comes to code splitting), such as independently cacheable stylesheets, sending duplicate css definitions when server-rendering (both in js + flushed css), but after a long time fighting the css fight with things like [extract-css-chunks-webpack-plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin), and even though Webpack 5 is slated to have better support for this stuff, I'm outa the game.

The above is the best I was able to come up with for a recent Sass project with global styles (which I haven't used in years), and it's very fast. I realize it has no signs of code splitting handling. I just thought I'd put it out there cuz I saw you were also doing the `sass-resources-loader` thing. Mine doesn't [follow `@import`](https://github.com/shakacode/sass-resources-loader/blob/master/src/utils/rewriteImports.js#L37) in the prepended variables, but I decided to get "low level" and make it as fast as I can, while not being dependent on outside libs--similar to what you meant by "remove human error."

Ima close this out cuz it sounds like u have some ideas of what to do. Sass resources loader by Shaka Code is a good pick, and what I picked too after TONS of research. I hadn't used css without modules, nor a bootstrap theme a in a very long time.

**Comment by zackkirsh** [comment]
Thanks this has given me some direction. 

Im trying to run babel-server, but with something like sass-resources-loader to actually inject all those mixens and such back into my imported stylesheets.

I had also though just injecting them as strings the same way you are with joinScss but i didnt think it would be performant :P 

However it sounds like you are getting some good results so Im going to try modifying your code into a babel sass loader. Ill make a repo and send you a link to it, in case you ever get the question again.

**Comment by faceyspacey** [comment]
As long as the prepended scss doesn't generate CSS it's very fast. It's basically the same thing as `@importing` mixins/vars, but a little bit faster as whatever scss tools you're using don't have to parse the scss and follow imports like `sass-resources-loader` does:

https://github.com/shakacode/sass-resources-loader/blob/master/src/utils/rewriteImports.js#L26-L38

If what you prepended did generate css, it would be very slow and mess up styles a bit (as well as browser performance) due to tons of duplicate styles--I had this problem initially.

**Comment by zackkirsh** [comment]
Oh yeah, you've gotta be very careful when using resource injection. I strictly only store color variables and mixins, absolutely no actual styles are ever injected - thus no performance hit. 

I think we both have experienced the troubles around css optimization, i must applaud your efforts, chunking is hard and in the end i think alot of style optimization still boils down to how a developer sets up their CSS. POSTCSS is awesome but theres just no real good solution to chunk optimization for stylesheets as a whole. 

Im ive also been looking at the roadmap for WP5 and i think the CSS thing is way overdue! With the new chunking system, hopefully it will work well
