### ISSUE TITLE
Doesn't play well with babel-plugin-dynamic-import-webpack

### ISSUE THREAD

**Issue by extronics** [faceyspacey/babel-plugin-universal-import#5]
I'm not sure whether this is the right place or whether this should be reported with `babel-plugin-dynamic-import-webpack`. 
It seems that these two packages conflict with each other: `universal-import` transforms the import statements if it's the only plugin. When `dynamic-import-webpack` gets added to the plugin list in `.babelrc` then `import` statements are transformed according to `dynamic-import-webpack`, effectively overwriting the changes from `universal-import`.

Some compiled sample code, original code looks like this:

```javascript
const LandingPage = connectLandingPage(universal(() => import('./containers/landingpage')));
```

both plugins:

```javascript
var LandingPage = (0, _reactUniversalComponent2.default)(new _promise2.default(function (resolve) {
  __webpack_require__.e/* require.ensure */(2).then((function (require) {
    resolve(__webpack_require__(679));
  }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
}));
```

`dynamic-import-webpack` only:

```javascript
var LandingPage = (0, _reactUniversalComponent2.default)(new _promise2.default(function (resolve) {
  __webpack_require__.e/* require.ensure */(2).then((function (require) {
    resolve(__webpack_require__(679));
  }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
}));
```

`universal-import` only:

```javascript
var LandingPage = (0, _reactUniversalComponent2.default)((0, _universalImport3.default)({
  id: './containers/landingpage',
  file: ' [...]/ssr/app/routes.js',
  load: function load() {
    return _promise2.default.all([__webpack_require__.e/* import() */(2).then(__webpack_require__.bind(null, 679)), (0, _importCss3.default)('containers/landingpage')]).then(function (proms) {
      return proms[0];
    });
  },
  path: function path() {
    return _path3.default.join(__dirname, './containers/landingpage');
  },
  resolve: function resolve() {
    return /*require.resolve*/(679);
  },
  chunkName: function chunkName() {
    return 'containers/landingpage';
  }
}));
```

As you can see, the transform only works if `universal-import` is alone. As a side effect, `webpack-flush-chunks` will then not see any named chunks anymore and never bundle the correct chunks with the initial page load.

This can also be reproduced with your `universal-demo` repository by just adding the `dynamic-import-webpack` plugin.

Also, the plugin order in .babelrc doesn't have any effect on this behaviour.

Any ideas how to solve this?

Btw: in my project, when using `universal-import` only, the code which is served to the client looks ok. But on the server, it complains about the keyword `import` being in the code. Is there any case where the compiled code form this plugin looks different, depending on whether it's served for the client or for node?

**Comment by faceyspacey** [comment]
What version of webpack are you using? I assume an old one, which is why you want to convert them to require.ensure.

If that's the case, I guess this won't work with`dynamic-import-webpack` because it simply won't be able to transpile `require.ensure`. That will have to be noted in the readme. 

Perhaps this one is what you want: 
https://github.com/airbnb/babel-plugin-dynamic-import-node

As it will make sure babel doesn't at least fail. You're still going to need a webpack version new enough to be able to transpile `import()`.

As for the server complaining, the above package may be the solution for that too. Or perhaps, that's the exact place it's the solution (since `import()` is only used on the client). The client will need a new enough webpack to be able to compile `import()`. I noted it somewhere in the docs--i think its 2.4.1 from about January. 

So my hunch this is an upgrade webpack issue--because you don't need that plugin you're using anymore.

**Comment by faceyspacey** [comment]
By the way, there is an update for when using a babel server:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/docs/babel-config.md

*.babelrc:*
```js
{
  "plugins": [[
    "universal-import", {
      "babelServer": true
    }]
}
```
Otherwise, with the latest versions of webpack you dont need anything but the `universal-import` plugin as `import()` is fully supported. So it's only when you have a babel server *(rather than a webpack server)* that you need to use additional plugins. And that said, you no longer do, as universal-import has you covered now via the `babelServer: true` option added to your `.babelrc`.
