### ISSUE TITLE
import()ed module is not executed until .then() or .catch() is called on it

### ISSUE THREAD

**Issue by hedgepigdaniel** [faceyspacey/babel-plugin-universal-import#50]
```javascript
// globalHaCKS.js

window.document.stateOverride13 = 'YOLO';

renderLegacyApp();
```

```javascript
// just_make_it_less_slow.js

import('./globalHaCKS.js'); // Doesn't work!

import('./globalHaCKS.js').then(); // Works :s
```

When using webpack's built in support for the `import()` statement, the imported module is executed as soon as the promise is created and the chunk is downloaded. With this package, it seems that the imported module is executed only when `.then()` or `.catch()` is called on the promise (even though either way the chunk is downloaded as soon as the promise is created).

This seems like an unnecessary and confusing breaking change compared to the way `import()` works in webpack. Any chance of changing it so that it is not necessary to call `.then()` or `.catch()` on the promise?

**Comment by ScriptedAlchemy** [comment]
This is something that’s been documented  in the caveats. 

Check out the Babel plugin readMe

Pretty much, you are not using a normal import function which webpack provides. It’s transformed into our universalImport 

While it is thennable, it’s not self evoking. “Then” in our context, is a function which executes “load”, which is a promise. 

Give this a read: https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/universalImport.js
———
To the discerning eye, you may be wondering if the return of import() is still thenable?? It is! However, if you don't call .then on it, somewhere (perhaps in the components like react-universal-component that you pass it to), then it won't perform the import. Since most of us are using modules, which we need to do something with in the then callback, that's not a problem. But if you happen to be importing a module that does its own setup, such as attaches something to the window object, well then you just need to call .then() to trigger it. That's a rare case these days, which is why we decided to go with the simplicity seen here. And yes, async await works too.

**Comment by faceyspacey** [comment]
Thanks @zackljackson ...couldn't have explained it better. Hope that helps @hedgepigdaniel

**Comment by hedgepigdaniel** [comment]
Thanks for that... I think I read that before and then forgot where it was. Who would have thought it was in the README haha.

Curious though, is that a choice so that its possible to do `universal(import('./module'))` rather than `universal(() => import('./module'))`, or is there some other reason why its necessary?

E.g in `universalImport.js` its easy to imagine that `load()` could be called immediately, with `.then()` and `.catch()` chaining things onto the potentially resolved promise later.

**Comment by ScriptedAlchemy** [comment]
@hedgepigdaniel Its an easy one to miss :) 
I think you can do it either way if i remember correctly. 

I can think of reasons to use a function though, In my case, i often use a custom component

`<UniversalComponent component={() => (import('../ExtraAssets/SomeShit'))}/>`

Essentially, i dont want to invoke universal in a prop, but pass it into the component which can then invoke it when its time. 

Do you get a particular issue when trying to pass it right in?

Remember, import() is transformed into something entirely different. we cant assume promises because we are catering for sync and async.

We also dont want to bind people to our conventions. We are considering universal HOC in numerous environments and supersets. 

That being said, ill look at the code again and give you a more accurate explanation if you desire.

We also accept pull requests 😉

**Comment by faceyspacey** [comment]
Yea, custom components or userland HOCs (which both achieve the same goal of re-use) is the reason. It allows all the generated aspects to be passed around as one ball/object.
