### ISSUE TITLE
Does this support IE11? Error with React child type

### ISSUE THREAD

**Issue by marnusw** [faceyspacey/babel-plugin-universal-import#9]
I have cloned the latest `dev` branch of [react-boilerplate ](https://github.com/react-boilerplate/react-boilerplate) which uses `react-loadable` and works correctly in IE11. After switching out `react-loadable` for `react-universal-component` and adding `universal-import` I saw this error when loading the site in IE11:

```
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `App__AppWrapper`.
```

The source is [here](https://github.com/marnusw/react-boilerplate/tree/universalImport), I have added only the one commit. There is no SSR and no CSS to extract so the related libraries from this suite is not used.

Do you have any idea what might be wrong? Did I miss a step in setting up the `universal-*` components?

**Comment by faceyspacey** [comment]
I ran it and it worked fine for me. See this screenshot:

![screen shot 2017-08-22 at 3 43 13 am](https://user-images.githubusercontent.com/154732/29561893-116b69b8-86ec-11e7-9972-6254299e134e.png)

Im showing that screenshot to show you the warning that would only appear if things are working correctly. That's a minor warning indicating there is no CSS stylesheet imported along with the js chunk. But it indicates that it's working

Are you using yarn? Delete your node_modules folder and try again using yarn. 

Otherwise, that error you pasted I've never seen before and is likely related to something else--perhaps something else you changed since your first commit. ...actually, i see, that's only IE11. I don't have IE11 on my current computer. But does this work outside of IE11? Are you sure you dont get that issue the way it was before in IE11? React Universal Component doesn't do any of the things below that might of triggered this error.

Here are the issues on stack overflow I see related to this:

- https://stackoverflow.com/questions/37997893/promise-error-objects-are-not-valid-as-a-react-child
- https://stackoverflow.com/questions/34919111/how-to-debug-this-error-uncaught-in-promise-error-objects-are-not-valid-as-a
- https://stackoverflow.com/questions/41604539/objects-are-not-valid-as-a-react-child


One other thing: you want to make your imports this:

```js
export default universal(() => import('../FeaturePage'), {
  loading: LoadingIndicator,
});
```

Notice how `FeaturePage` is in the path--that allows different chunks to be created for each page. Currently all 3 pages dynamically imported were in the same chunk. That's something I should better document.

**Comment by faceyspacey** [comment]
One other thing: I would find it weird for React to print that error only in IE11. Ideally they would warn you have something that won't work in other browsers *in all browsers.* Which is why I'm thinking the issue might be something else--i.e. that you added some additional code to display an object in JSX (where only strings or numbers are accepted) as those stackoverflow issues indicate.

**Comment by marnusw** [comment]
Thanks for the very details response and taking the time to see if you can reproduce this @faceyspacey. 

This was working in every other browser I tested with except for IE11 specifically. Looking at those object keys listed in the error it looks like a child react component is being used as an object rather than a proper React component instance which is really weird.

I truly didn't change anything else, I literally only swapped react-loader for react-universal-component and your plugin, but I'm going to test it again just to be 100% sure and I'll let you know what I find.

Your note on `() => import('../FeaturePage')` is interesting. I hadn't picked up on that elsewhere in the docs (the ones I read anyway :smile:). I'll see if this affects the issue as well, it might just be that things get bundled slightly differently with this option and that IE won't choke on it.

**Comment by faceyspacey** [comment]
If u can open up node_modules/react-universal-component/dist/index.js and make the render method always return some static div or something. If that fixes the issue we know the issue is coming from there. Then replace that with logging of what it is rendering and we should know what's wrong with the React elements it's trying to render.

**Comment by marnusw** [comment]
I did some more digging and the problem is an interesting one: It seems the import plugin is causing the Symbol polyfill to go wrong in IE11. React uses a `$$typeof: Symbol(react.element)` on a rendered component to identify it as an element, and because that value isn't correct React identifies the child as an Object and not an element, throwing that error.

I have managed to reproduce the same problem in Chrome by deleting `window.Symbol` to force the polyfill, in `index.html`:

```html
<script>
  delete window.Symbol;
</script>
```

I noticed the error is not triggered on the component rendered by `react-universal-component`, but the top-level component in `app/containers/App.js`. Furthermore, simply removing the import plugin from the babel config makes the issue go away. The chunk names disappear and I assume CSS chunks won't work in this case since the universal call isn't transpiled, but async loading of the chunks still works in this case. So it looks like the import plugin changes the import context in some way that causes `babel-polyfill`/`core-js` not to function properly.

You can reproduce this by fetching the new version of the [`universalImport`](https://github.com/marnusw/react-boilerplate/commits/universalImport) branch and checking out `universalImport` or `universalImport~1` where the only change is adding the plugin to the babel plugins list.

Deleting the Symbol from window will probably allow you to reproduce this in your own examples as well.

This is the extent of my investigation so far. I'll spend some more time on it when I can, but I thought I'd share this much in case you have any insights at this point.

**Comment by faceyspacey** [comment]
Thanks for doing this research. I still don't know how the plugin can have anything to do with breaking the `Symbol` function. It's only used in the babel plugin itself, whose AST-related code never appears client side. You can search the code for *"Symbol"*:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js

It may end up one of those things where we think the issue is one thing, but the it ends up being something entirely different. Here's another thing you can try:

- go to the end of the babel plugin file: https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L182
- comment out the items in that array until the issue doesn't exist anymore (though eventually it might will break things server-side)
- that would help us pinpoint what area of the code that is the problem. 
- lastly, there are these 2 files that the plugin imports, which will be used client side: 

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/universalImport.js

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/importCss.js

I'm actually thinking now that one of them causes the issue, as the babel plugin generates pretty standard code, minus maybe the `Promise.all` stuff. 

So within `node_modules/babel-plugin-universal-import/importCss.js` and `universalImport.js`, try deleting parts of that code until the error goes away.

**Comment by faceyspacey** [comment]
Also because you're mentioning polyfills, it makes me think that the issue is related to promises, as that's the only thing that must be polyfilled for this to work. Promises are generated by the plugin and imported in the 2 files I just mentioned. So perhaps it has to do with the polyfill not appearing in the correct order or something like that, as the babel-plugin imports the 2 files at the top of the corresponding file. I hope that's not it. Putting the polyfill at the top of the webpack entry point's array, rather than requiring it within application code should solve that.

**Comment by faceyspacey** [comment]
I did the delete Symbol thing, and I found the issue. It's this line:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/universalImport.js#L30

it doesnt in fact throw an error. It works fine. But if you comment it out, the issue doesnt occur. Bizarre!

I've tried deleting all the code that is required by it, and it still happens. It's really confusing. 

One thing I noticed is that the boilerplate is running on 6 months old 2.6 webpack. That might be it. My laptop is dying and I'm not at home or I'd try the upgrade now.

**Comment by faceyspacey** [comment]
Another thing to keep in mind: the dll stuff him this boilerplate means u won't be dealing with updates code if u play with the things in node modules. I've used excludes in the package.json and rebuilt the dll to insure I can update React Universal Component code and see the changes.

There's a lot going on in this repo. It likely has to do with the combination of stuff it's doing. It's also an old repo. Webpack is at like 3.5 now. People seem to be using the autodll package now. Etc. It's a tough call as to why simply using that internal webpack require method is causing this issue, especially since if u make the required component do almost nothing, the issue still occurs.

There are other imports in the code that aren't wrapped in ruc. Perhaps the plugin is breaking those. That's my next thought.

**Comment by marnusw** [comment]
I actually updated to webpack 3.5.5 before trying all this, so that's not it. :-(

I'm also a little out of date on webpack still, I haven't hear of the autodll package but will check it out!

I'll read through all your posts properly and continue fiddling this evening.

**Comment by faceyspacey** [comment]
You also may wanna consider using the redux-first router demo or boilerplate. I mean, ur starting a new app from scratch right? Redux-First Router is *"the router"* when it comes to Redux apps (my user's words, not mine). Check it:

https://github.com/faceyspacey/redux-first-router

there is 2 links at the top of the repo for the demo and the boilerplate. the demo is much more feature-packed, but both can be used as boilerplates. 

That said I do wanna fix ur issue, but it may be irrelevant if you like RFR.

**Comment by marnusw** [comment]
Yeah, thanks for that. I took a brief look at RFR and it looks really promising. I will definitely try it out at some point. I have actually converted an existing project we used to build with gulp & browserify to webpack so it's not entirely new, but switching routers is not so big a task that it can't be considered. Other projects are upcoming too... When I started digging into webpack I worked from react-boilerplate, so when I needed a clean simple app it seemed a good test case for this particular issue. Also because it was working correctly with `react-loadable`.

Anyway... The first thing I tried just now was to move `babel-polyfill` from an import in `app.js` to the webpack `entry` config. **And it solved the issue!!**

So whatever the problem might be it seems the order of initialisation was off.

My main concern for raising this issue was not to make my particular setup work, but rather to ensure that the `universal-*` libraries do support IE11, which it does. I'm still curious to know exactly what is happening here though. Either way, documenting this caveat might be worthwhile.

**Comment by faceyspacey** [comment]
Excellent. Code that requires the babel polyfill simply runs before it exists because babel lets u inject imports. I'll see if I have a choice to put it near the bottom of the static imports within a file. 

The fact that the error js not more specific likely has to do with a combination of crappy promise error smothering and crappy React reconcialiation call stacks.
